# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: vllm-disagg-kvbm-2p2d
spec:
  services:
    Frontend:
      dynamoNamespace: vllm-disagg-kvbm-2p2d
      componentType: frontend
      replicas: 1
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:my-tag
    VllmDecodeWorker:
      dynamoNamespace: vllm-disagg-kvbm-2p2d
      envFromSecret: hf-token-secret
      componentType: worker
      replicas: 2
      resources:
        limits:
          gpu: "1"
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:my-tag
          workingDir: /workspace/components/backends/vllm
          command:
          - python3
          - -m
          - dynamo.vllm
          args:
            - --model
            - Qwen/Qwen3-8B
            - --gpu-memory-utilization
            - "0.3"
            - --disable-log-requests
            - --max-model-len
            - "32000"
            - --enforce-eager
    VllmPrefillWorker:
      dynamoNamespace: vllm-disagg-kvbm-2p2d
      envFromSecret: hf-token-secret
      componentType: worker
      replicas: 2
      resources:
        requests:
          gpu: "1"
          memory: "200Gi"
        limits:
          gpu: "1"
          memory: "250Gi"
      envs:
        - name: DYN_KVBM_CPU_CACHE_GB
          value: "100"
        - name: DYN_KVBM_BARRIER_ID_PREFIX
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:my-tag
          workingDir: /workspace/components/backends/vllm
          command:
          - python3
          - -m
          - dynamo.vllm
          args:
            - --model
            - Qwen/Qwen3-8B
            - --is-prefill-worker
            - --gpu-memory-utilization
            - "0.3"
            - --disable-log-requests
            - --max-model-len
            - "32000"
            - --enforce-eager
            - --connector
            - kvbm
            - nixl
