# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-config
data:
  config.yaml: |
    enable_attention_dp: true
    cuda_graph_config:
        max_batch_size: 800
        enable_padding: true
    kv_cache_config:
      enable_block_reuse: false
    stream_interval: 20
    moe_config:
        backend: CUTLASS